version: "3.9"
services:
  app:
    stdin_open: true
    tty: true
    env_file: .env
    build:
      context: .
      args:
        - USER
        - UID
    entrypoint: ./entrypoint.sh
    working_dir: /app
    ports:
      - "3000:3000"
    command: "./start.sh"
    volumes:
      - .:/app
      - gems:/app/tmp/gems
    depends_on:
    - db
    - redis
    - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: cep_development
    volumes:
      - mongodata:/etc/mongo
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: latam-gateway
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    hostname: redis
    volumes:
      - redis-data:/data
volumes:
  mongodata:
  pgdata:
  redis-data:
  gems:
